CREATE TABLE public."Article" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Link" text NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Page_count" integer NOT NULL
);

CREATE TABLE public."ArticleContent" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_article" bigint,
    "Page_number" integer NOT NULL,
    "Text" character varying NOT NULL, 
  CONSTRAINT "fk_article" FOREIGN KEY ("Id_article") REFERENCES public."Article"("Id") ON DELETE CASCADE
);

CREATE TABLE public."UserToArticles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_user" bigint ,
    "Progress" integer DEFAULT 1,
    "Id_article" bigint NOT NULL,
   CONSTRAINT "fk_user" FOREIGN KEY ("Id_user") REFERENCES public."User"("Id") ON DELETE CASCADE,
   CONSTRAINT "fk_article" FOREIGN KEY ("Id_article") REFERENCES public."Article"("Id") ON DELETE CASCADE
);

CREATE TABLE public."User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(50) NOT NULL,
    "Password" character varying(30) NOT NULL,
    "Rating" real DEFAULT 5
);

CREATE TABLE public."Collection" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name " character varying(50) NOT NULL,
    "Id_user" bigint,
  CONSTRAINT "fk_user" FOREIGN KEY ("Id_user") REFERENCES public."User"("Id") ON DELETE CASCADE
);

CREATE TABLE public."Card" (
    "Id" bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Word" character varying(50) NOT NULL,
    "Definition" character varying(150) NOT NULL,
    "Id_collection" bigint,
    "Memory_degree" real DEFAULT 0,
    "Latest_view_date" date DEFAULT NULL,
  CONSTRAINT "fk_collection" FOREIGN KEY ("Id_collection") REFERENCES public."Collection"("Id") ON DELETE CASCADE
);