CREATE TABLE public."Article" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Link" text NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Page_count" integer NOT NULL
);

CREATE TABLE public."ArticleContent" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_article" bigint,
    "Page_number" integer NOT NULL,
    "Text" character varying NOT NULL, 
  CONSTRAINT "fk_article" FOREIGN KEY ("Id_article") REFERENCES public."Article"("Id") ON DELETE CASCADE
);

CREATE TABLE public."User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(50) NOT NULL,
    "Password" character varying(30) NOT NULL,
    "Rating" real DEFAULT 5
);

CREATE TABLE public."UserToArticles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Id_user" bigint ,
    "Progress" integer DEFAULT 1,
    "Id_article" bigint NOT NULL,
   CONSTRAINT "fk_user" FOREIGN KEY ("Id_user") REFERENCES public."User"("Id") ON DELETE CASCADE,
   CONSTRAINT "fk_article" FOREIGN KEY ("Id_article") REFERENCES public."Article"("Id") ON DELETE CASCADE
);

CREATE TABLE public."Collection" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name " character varying(50) NOT NULL,
    "Id_user" bigint,
  CONSTRAINT "fk_user" FOREIGN KEY ("Id_user") REFERENCES public."User"("Id") ON DELETE CASCADE
);

CREATE TABLE public."Card" (
    "Id" bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Word" character varying(50) NOT NULL,
    "Definition" character varying(150) NOT NULL,
    "Id_collection" bigint,
    "Memory_degree" real DEFAULT 0,
    "Latest_view_date" date DEFAULT NULL,
  CONSTRAINT "fk_collection" FOREIGN KEY ("Id_collection") REFERENCES public."Collection"("Id") ON DELETE CASCADE
);

INSERT INTO "User"("Name", "Password") VALUES ('Nick', 123456);
INSERT INTO "User"("Name", "Password") VALUES ('Daria', 987654321);

INSERT INTO public."Article"("Link", "Name", "Page_count")
  VALUES ('Google.by', 'Hello hell', 2);
INSERT INTO public."Article"("Link", "Name", "Page_count")
  VALUES ('wiggle.by', 'Gucci', 3);

INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (1, 1, '');
INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (1, 2, '');

INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (1, 1, 'A harpoon is a long spear-like projectile used in fishing, whaling, sealing, and other hunting activities to shoot, kill, and capture large fish or marine mammals such as seals, sea cows and whales. This photograph shows two views of a 19th-century Inuit harpoon, known as an unaaq in Inuktitut, from Labrador in present-day Canada.');
INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (1, 2, 'The poem begins with Claudian recounting the career of Eutropius, an Eastern Roman politician and court eunuch, who became highly influential in the Imperial court. .');

INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (2, 1, 'He critiques Eutropius for his important role in the military of the Eastern Empire, considering him too effeminate to run an army, claiming that he should have taken up spinning instead.');
INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (2, 2, 'Claudian believed that an influential Western Roman general named Flavius Stilicho was the only man capable of protecting and uniting both the Western and Eastern Empires. He viewed Eutropius as an enemy who prevented Stilicho from accomplishing these goals.');
INSERT INTO public."ArticleContent"("Id_article", "Page_number", "Text")
  VALUES (2, 3, 'Most information about military and political history have been preserved in secular historians works. When writing of events familiar to them or their acquaintances, they are mostly reliable. Aurelius Victor and an unknown author completed short imperial biographies in the second half of the 4th century, allegedly using a common source.');

INSERT INTO public."UserToArticles"("Id_article","Id_user")
  VALUES (1,1);
INSERT INTO public."UserToArticles"("Id_article","Id_user")
  VALUES (1,2);
INSERT INTO public."UserToArticles"("Id_article","Id_user")
  VALUES (2,1);
INSERT INTO public."UserToArticles"("Id_article","Id_user")
  VALUES (2,2);